name: Lint ES mod

on:
  push:
    branches:
      - main

env:
  SDK_VERSION: "8.1.3"
  GOOGLE_DRIVE_ID: "1MM3B6VRDXJDwQphj_sWuG8AthqIu8s-y"
  ES_VER: "6"
  PROJECT_NAME: "thld"

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up cache for SDK
        id: cache-sdk
        uses: actions/cache@v3
        with:
          path: "~/.renpy-sdk"
          key: ${{ runner.os }}-renpy-sdk-${{ env.SDK_VERSION }}

      - name: Download Ren'Py SDK
        if: steps.cache-sdk.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/.renpy-sdk
          wget -q "https://www.renpy.org/dl/${{ env.SDK_VERSION }}/renpy-${{ env.SDK_VERSION }}-sdk.tar.bz2"
          tar -xjf "renpy-${{ env.SDK_VERSION }}-sdk.tar.bz2" -C ~/.renpy-sdk
          rm "renpy-${{ env.SDK_VERSION }}-sdk.tar.bz2"

      - name: Set up cache for Game
        id: cache-game
        uses: actions/cache@v3
        with:
          path: "./"
          key: ${{ runner.os }}-everlasting-summer-${{ env.ES_VER }}-${{ env.GOOGLE_DRIVE_ID }}

      - name: Download Everlasting Summer
        if: steps.cache-game.outputs.cache-hit != 'true'
        run: |
          pip install gdown
          gdown --id "${{ env.GOOGLE_DRIVE_ID }}" -O "Everlasting Summer.zip"
          unzip -q "Everlasting Summer.zip" -d "./"
          rm "Everlasting Summer.zip"
          
  basic-lint:
    runs-on: ubuntu-latest
    needs: download
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up cache for SDK
        id: cache-sdk
        uses: actions/cache@v3
        with:
          path: "~/.renpy-sdk"
          key: ${{ runner.os }}-renpy-sdk-${{ env.SDK_VERSION }}

      - name: Set up cache for Game
        id: cache-game
        uses: actions/cache@v3
        with:
          path: "./"
          key: ${{ runner.os }}-everlasting-summer-${{ env.ES_VER }}-${{ env.GOOGLE_DRIVE_ID }}

      - name: Copy mod files to game directory
        run: |
          mkdir -p "./Everlasting Summer/game/$PROJECT_NAME"
          cp -r ./code ./images ./sounds "./Everlasting Summer/game/$PROJECT_NAME"
          echo "Folder contents:"
          ls "./Everlasting Summer/game"

      - name: Run Ren'Py Lint
        run: |
          ~/.renpy-sdk/renpy-${{ env.SDK_VERSION }}-sdk/renpy.sh "./Everlasting Summer/game/" lint lint_report.txt
        shell: bash

      - name: Upload Lint Report
        uses: actions/upload-artifact@v3
        with:
          name: lint-report
          path: lint_report.txt

      - name: Display Lint Report
        run: |
          cat lint_report.txt