name: Lint ES mod

on:
  push:
    branches:
      - main

jobs:
  lint:
    uses: paych3ck/es_mod_workflow/.github/workflows/lint_es_mod.yml@v1.0.0
    with:
      project_name: "thld"
      sdk_version: "8.1.3"
      google_drive_id: "1MM3B6VRDXJDwQphj_sWuG8AthqIu8s-y"
      es_ver: "7"
      grammar_check_files: "code/threshold_scenario.rpy"